---
title: "Stock Back Test 6.0"
author: "Ethan"
output:
  html_document:
    df_print: paged
    toc: yes
    theme: yeti
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(knitr)
library(ggplot2)
library(quantmod)
library(tidyverse)
library(DT)
library(tidyquant)
```

# Rules

```{r}
BackTest = function(stock_code, stock_start, stock_end, 
                    stock_interval = 'weekly', adj = TRUE)
{
  # Import data
  dat = getSymbols(stock_code, from = stock_start, to = stock_end, 
                    auto.assign = FALSE, periodicity = stock_interval)
  cat(stock_code, stock_interval, "from", stock_start, "to", stock_end)
  
  # Format Changing
  dat = data.frame(date=index(dat), coredata(dat))
  dat = dat[, 1:5]
  names(dat) = c("date", "open", "high", "low", "close")
  
  # Data Cleaning
  dat = filter(dat, open != high | high != low | low != close)
  dat = dat[complete.cases(dat), ]
  
  # Change date format
  dat$date = as.Date(dat$date, "%Y-%m-%d")
  
  # judge: high or low to be the first
  dat = dat %>% 
    mutate(first = high) %>%
    mutate(second = low)

  # Tactic
  dire = "flat"
  first = "none"
  trade_date = NULL
  trade_cost = NULL
  trade_sell = NULL
  for(i in 2:nrow(dat))
  {
    ## open
    if(dire == "flat")
    {
      if(dat$open[i] < dat$low[i-1])
      {
        dire = "short"
        kind = "trend"
        trade_date = c(trade_date, dat$date[i])
        trade_dire = dire
        trade_kind = kind
        trade_cost = c(trade_date, dat$open[i])
      }
      if(dat$open[i] > dat$high[i-1])
      {
        dire = "long"
        kind = "trend"
        trade_date = c(trade_date, dat$date[i])
        trade_dire = dire
        trade_kind = kind
        trade_cost = c(trade_date, dat$open[i])
      }
    }
    if(dire == "long")
    {
      if(dat$open[i] < dat$low[i-1])
      {
        dire = "flat"
        trade_sell = c(trade_sell, dat$open[i])
      }
      if(dat$open[i] > dat$high[i-1] & kind == "fluct")
      {
        dire = "flat"
        trade_sell = c(trade_sell, dat$open[i])
      }
    }
    if(dire == "short")
    {
      if(dat$open[i] < dat$low[i-1] & kind == "fluct")
      {
        dire = "flat"
        trade_sell = c(trade_sell, dat$open[i])
      }
      if(dat$open[i] > dat$high[i-1])
      {
        dire = "flat"
        trade_sell = c(trade_sell, dat$open[i])
      }  
    }

    ## low, high, and close
    for(j in 1:3)
    {
      #--> specify (step 1-3)
      if(j == 1)
      {
        if(dat$open[i] < dat$close[i])
        {
          dat$first[i] = dat$open[i]
          dat$second[i] = dat$low[i]
        }
        if(dat$open[i] >= dat$close[i])
        {
          dat$first[i] = dat$open[i]
          dat$second[i] = dat$high[i]
        }
      }
      if(j == 2)
      {
        if(dat$open[i] < dat$close[i])
        {
          dat$first[i] = dat$low[i]
          dat$second[i] = dat$high[i]
        }
        if(dat$open[i] >= dat$close[i])
        {
          dat$first[i] = dat$high[i]
          dat$second[i] = dat$low[i]
        }
      }
      if(j == 3)
      {
        if(dat$open[i] < dat$close[i])
        {
          dat$first[i] = dat$high[i]
          dat$second[i] = dat$close[i]
        }
        if(dat$open[i] >= dat$close[i])
        {
          dat$first[i] = dat$low[i]
          dat$second[i] = dat$close[i]
        }
      }
      #--> down middle
      if(dat$first[i] < dat$low[i-1] & dat$second[i] >= dat$low[i-1] & dat$second[i] <= dat$high[i-1])
      {
        if(dire == "flat")
        {
          dire = "long"
          kind = "fluct"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$low[i-1])
        }
        if(dire == "long")
        {
          return("impossible")
        }
      }
      #--> down up
      if(dat$first[i] < dat$low[i-1] & dat$second[i] > dat$high[i-1])
      {
        if(dire == "flat")
        {
          dire = "long"
          kind = "fluct"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$low[i-1])
          dire = "flat"
          trade_sell = c(trade_sell, dat$high[i-1])
        }
        if(dire == "long")
        {
          return("impossible")
        }
        if(dire == "short")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$high[i-1])
        }
      }
      #--> middle down
      if(dat$first[i] >= dat$low[i-1] & dat$first[i] <= dat$high[i-1] & dat$second[i] < dat$low[i-1])
      {
        if(dire == "flat")
        {
          dire = "short"
          kind = "trend"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$low[i-1])
        }
        if(dire == "long")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$low[i-1])
        }
        if(dire == "short" & kind == "fluct")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$low[i-1])
        }
      }
      #--> middle up
      if(dat$first[i] >= dat$low[i-1] & dat$first[i] <= dat$high[i-1] & dat$second[i] > dat$low[i-1])
      {
        if(dire == "flat")
        {
          dire = "long"
          kind = "trend"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$high[i-1])
        }
        if(dire == "long" & kind == "fluct")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$high[i-1])
        }
        if(dire == "short")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$low[i-1])
        }
      }
      #--> up down
      if(dat$first[i] > dat$high[i-1] & dat$second[i] < dat$low[i-1])
      {
        if(dire == "flat")
        {
          dire = "short"
          kind = "fluct"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$high[i-1])
          dire = "flat"
          trade_sell = c(trade_sell, dat$low[i-1])
        }
        if(dire == "long")
        {
          dire = "flat"
          trade_sell = c(trade_sell, dat$low[i-1])
        }
        if(dire == "short")
        {
          return("impossible")
        }
      }  
      #--> up middle
      if(dat$first[i] > dat$high[i-1] & dat$second[i] >= dat$low[i-1] & dat$second[i] <= dat$high[i-1])
      {
        if(dire == "flat")
        {
          dire = "short"
          kind = "fluct"
          trade_date = c(trade_date, dat$date[i])
          trade_dire = dire
          trade_kind = kind
          trade_cost = c(trade_date, dat$high[i-1])
        }
        if(dire == "short")
        {
          return("impossible")
        }
      }
    }
  }
  trade = data.frame(trade_date, trade_dire, trade_kind, trade_cost, trade_sell)
  
  # Margin and Margin rate
  margin = NULL
  margin_rate = NULL
  for(i in 1:nrow(trade))
  {
    if(trade_dire[i] == "long")
    {
      margin = c(margin, trade_sell[i] - trade_cost[i])
      margin_rate = c(margin_rate, (trade_sell[i] - trade_cost[i]) / trade_cost[i])
    }
    if(trade_dire[i] == "short")
    {
      margin = c(margin, trade_cost[i] - trade_sell[i])
      margin_rate = c(margin_rate, (trade_cost[i] - trade_sell[i]) / trade_cost[i])
    }
  }
  trade = cbind(trade, margin, margin_rate)
  colnames(trade) = c("date", "direction", "kind", "cost", "sell", "margin", "margin_rate")
  
  # Plot: Margin
  p_margin = ggplot(trade) +
    geom_point(mapping = aes(x = date, y = margin_rate)) +
    geom_abline(slope = 0, intercept = 0, color = "red")
  
  # Plot: buy and sell points
  p_points = dat %>% 
    ggplot(aes(x = date, y = close)) +
    geom_candlestick(aes(open = open, high = high, low = low, close = close), 
                     colour_up = "tomato", colour_down = "green",
                     fill_up = "tomato", fill_down = "green") +
    geom_point(data = trade, mapping = aes(x = date, y = cost), shape = 3) +
    geom_point(data = trade, mapping = aes(x = date, y = sell), shape = 4) +
    theme_tq()
  
  # Summary
  margin = sum(trade$margin, na.rm = TRUE)
  market = dat$close[nrow(dat)] - dat$close[1]
  sum_margin = data.frame(margin = round(margin, 3),
                          margin_rate = round(margin / mean(dat$close), 3),
                          market = market,
                          market_rate = round(market / mean(dat$close), 3))
  
  # Digits
  dat$margin = dat$margin %>% 
    round(3)
  dat$margin_rate = dat$margin_rate %>% 
    round(3)
  
  # Return
  outcome = list("data" = dat, "sum_trigger" = sum_trigger, "sum_margin" = sum_margin, 
                 "p_margin" = p_margin, "p_points" = p_points)
  return(outcome)
}
```

# 报告

## 各种股票周K表现

```{r}
stock_start = "2010-01-01"
stock_end = "2019-11-07"
stock_code = c("^IXIC", "^GSPC", "^DJI", "^RUT", "600519.SS", "2328.HK", "159901.SZ", "000001.SZ", "600019.SS", "601857.SS", "0941.HK", "0241.HK", "045340.KQ", "0215.HK")
frame = c()
for(i in stock_code)
{
  list = BackTest(i, stock_start, stock_end, stock_interval = 'weekly')
  frame = rbind(frame, list$sum_margin)
}
sum = apply(frame, 2, mean)

frame %>% 
  rbind(sum) %>% 
  cbind(c(stock_code, NA)) %>% 
  datatable()

```

## 剧烈下跌：周K： 每月表现

```{r}
stock_code = "000001.SS"
row = c()
for(i in 1:8)
{
  stock_start = paste0("2018-0", i, "-01")
  stock_end = paste0("2018-0", i + 1, "-01")
  list = BackTest(stock_code, stock_start, stock_end, stock_interval = 'weekly')
  row = rbind(row, list$sum_margin)
}

frame = cbind(row, c(1:8))

sum = apply(frame, 2, sum)

frame %>% 
  rbind(sum) %>% 
  datatable()
```

## 月K报告

```{r}
stock_code = "0941.HK"
stock_start = "2012-01-01"
stock_end = "2019-11-07"
list = BackTest(stock_code, stock_start, stock_end, stock_interval = 'monthly')
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Plot of margin

```{r}
list$p_margin
```

Buy and Sell points

```{r}
list$p_points
```

Data

```{r}
datatable(list$data)
```

## 周K报告

```{r}
list = BackTest(stock_code, stock_start, stock_end, stock_interval = 'weekly')
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Plot of margin

```{r}
list$p_margin
```

Buy and Sell points

```{r}
list$p_points
```

Data

```{r}
datatable(list$data)
```

## 日K报告

```{r}
list = BackTest(stock_code, stock_start, stock_end, stock_interval = 'daily')
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Plot of margin

```{r}
list$p_margin
```

Buy and Sell points

```{r}
list$p_points
```

Data

```{r}
datatable(list$data)
```






