---
title: "股票回测2.0"
author: "吴宇翀"
output:
  html_document:
    df_print: paged
    toc: yes
    theme: yeti
---

# 回测

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(knitr)
library(ggplot2)
library(quantmod)
library(tidyverse)
library(Tushare)
library(DT)
```

```{r}
token = "b7ac41ebc8f9ec8f772a17fd378f9f2f93b9d810a961f7fee794b8b8"
api = pro_api(token)
```

```{r}
BackTest = function(stock_code, stock_start, stock_end, proportion = 0.5, stock_interval = 'monthly', adj = "qfq", stop_loss = TRUE, proportion_loss = 0, fix_loss = 0)
{
  dat <- getSymbols(stock_code, from = stock_start, to = stock_end, auto.assign=FALSE, api.key = "23df16b0153d591648bac006196f7a9fa380908a", periodicity = stock_interval)
  chartSeries(dat, type = "candlesticks", up.col='red', dn.col='green', theme="white", name = stock_code, TA = NULL)
  cat(stock_code, stock_interval, "from", stock_start, "to", stock_end, "adjusted" ,"stop_loss:", stop_loss, "fix_loss", fix_loss, "-----------------")
  
  # Format Changing
  dat = data.frame(date=index(dat), coredata(dat))
  dat = dat[, 1:6]
  names(dat) = c("trade_date", "open", "high", "low", "close", "volume")
  
  # Data Cleaning
  dat = filter(dat, open != high || high != low || low != close)
  dat = dat[complete.cases(dat), ]
  
  # Focast
  pre_high = c(NA, NA)
  pre_low = c(NA, NA)
  for(i in 3:nrow(dat))
  {
    pre_high = c(pre_high, 2 * dat$high[i-1] - dat$high[i-2])
    pre_low = c(pre_low, 2 * dat$low[i-1] - dat$low[i-2])
  }
  dat = cbind(dat, pre_high, pre_low)
  
  # Delete NA
  dat = dat[-c(1,2),]
  
  # Swap high and low in a specific situation
  for(i in 1:nrow(dat))
  {
    if(dat$pre_high[i] < dat$pre_low[i])
    {
      swap = dat$pre_high[i]
      dat$pre_high[i] = dat$pre_low[i]
      dat$pre_low[i] = swap
    }
  }
  
  # Change date format
  dat$trade_date = as.Date(dat$trade_date, "%Y-%m-%d")
  
  # Accuracy
  accuracy = c()
  for(i in 1:nrow(dat))
  {
    if(dat$close[i] <= dat$pre_high[i] & dat$close[i] >= dat$pre_low[i])
    {
      accuracy = c(accuracy, "within")
    }
    else if(dat$close[i] < dat$pre_low[i])
    {
      accuracy = c(accuracy, "over_estimate")
    }
    else if(dat$close[i] > dat$pre_high[i])
    {
      accuracy = c(accuracy, "under_estimate")
    }
  }
  accuracy = as.factor(accuracy)
  dat = cbind(dat, accuracy)
  
  # Plot: forcast
  p = ggplot(dat) +
    geom_line(mapping = aes(x = trade_date, y = close), color = "black") +
    geom_line(mapping = aes(x = trade_date, y = pre_high), color = "red", linetype = "dashed") +
    geom_line(mapping = aes(x = trade_date, y = pre_low), color = "blue", linetype = "dashed")
  
  # threshold
  dat = dat %>% 
    mutate(threshold = pre_low + (pre_high - pre_low) * proportion)
    
  # Tactic: bought or not and cost if bought
  bought = c(FALSE)
  cost = c(NA)
  for(i in 2:nrow(dat))
  {
    if(dat$close[i-1] < dat$threshold[i])
    {
      bought = c(bought, TRUE)
      cost = c(cost, dat$close[i-1])
    }
    else
    {
      bought = c(bought, FALSE)
      cost = c(cost, NA)
    }
  }
  dat = cbind(dat, bought, cost)
  
  # Tactic: sell and stop_loss
  sell = c(NA)
  for(i in 2:nrow(dat))
  {
    if(dat$bought[i] == TRUE)
    {
      sell = c(sell, dat$close[i])
    }
    else
    {
      sell = c(sell, NA)
    }
  }
  dat = cbind(dat, sell)
  
  # Tactic: stop_loss
  if(stop_loss == FALSE)
  {
    trigger = NA
  }
  if(stop_loss == TRUE)
  {
    trigger = c("none")
    for(i in 2:nrow(dat))
    {
      if(dat$bought[i] == TRUE && dat$open[i] < dat$pre_low[i] - proportion_loss * (dat$pre_high[i] - dat$pre_low[i]) - fix_loss * dat$pre_low[i])
      {
        trigger = c(trigger, "beginning")
        dat$sell[i] = dat$open[i]
      }
      else if(dat$bought[i] == TRUE && dat$low[i] < dat$pre_low[i] - proportion_loss * (dat$pre_high[i] - dat$pre_low[i]) - fix_loss * dat$pre_low[i])
      {
        trigger = c(trigger, "during")
        dat$sell[i] = dat$pre_low[i]
      }
      else if(dat$bought[i] == TRUE)
      {
        trigger = c(trigger, "within")
      }
      else
      {
        trigger = c(trigger, "none")
      }
    }
    trigger = as.factor(trigger)
    dat = cbind(dat, trigger)
  }
  
  # Margin and Margin rate
  margin = NA
  dat = cbind(dat, margin)
  for(i in 1:nrow(dat))
  {
    if(dat$bought[i] == TRUE)
    {
      dat$margin[i] = dat$sell[i] - dat$cost[i]
    }
  }
  margin_rate = NA
  dat = cbind(dat, margin_rate)
  for(i in 1:nrow(dat))
  {
    if(dat$bought[i] == TRUE)
    {
      dat$margin_rate[i] = (dat$sell[i] - dat$cost[i]) / dat$cost[i]
    }
  }
  
  # Plot: Margin
  dat_margin = dat %>% 
    filter(bought == TRUE)
  p_margin = ggplot(dat_margin) +
    geom_point(mapping = aes(x = trade_date, y = margin_rate)) +
    geom_abline(slope = 0, intercept = 0, color = "red")
  
  # Summary
  sum_trigger = summary(trigger)
  margin = sum(dat$margin, na.rm = TRUE)
  market = dat$close[nrow(dat)] - dat$close[1]
  sum_margin = data.frame(margin = round(margin, 3),
                          margin_rate = round(margin / mean(dat$close), 3),
                          market = market,
                          market_rate = round(market / mean(dat$close), 3))
  sum_accuracy = summary(accuracy)
  
  # Digits
  dat$margin = dat$margin %>% 
    round(3)
  dat$margin_rate = dat$margin_rate %>% 
    round(3)
  
  # Return
  outcome = list("data" = dat, "plot" = p, "sum_accuracy" = sum_accuracy, "sum_trigger" = sum_trigger, "sum_margin" = sum_margin, "p_margin" = p_margin)
  return(outcome)
}
```

# 各种股票周K表现

```{r}
stock_start = "2010-01-01"
stock_end = "2019-01-01"
stock_code = c("^IXIC", "^GSPC", "^DJI", "^RUT", "600519.SS", "2328.HK", "159901.SZ")
frame = c()
for(i in stock_code)
{
  list = BackTest(i, stock_start, stock_end, proportion = 0.5, stop_loss = TRUE, fix_loss = 0.035, stock_interval = 'weekly')
  frame = rbind(frame, list$sum_margin)
}
11
sum = apply(frame, 2, mean)

frame %>% 
  rbind(sum) %>% 
  cbind(c(stock_code, NA)) %>% 
  datatable()

```

# IXIC周K： 每月表现

```{r}5
stock_code = "^IXIC"
row = c()
for(i in 1:8)
{
  stock_start = paste0("2016-0", i, "-01")
  stock_end = paste0("2016-0", i + 1, "-01")
  list = BackTest(stock_code, stock_start, stock_end, proportion = 0.5, stop_loss = TRUE, fix_loss = 0.035, stock_interval = 'weekly')
  row = rbind(row, list$sum_margin)
}

frame = cbind(row, c(1:8))

sum = apply(frame, 2, sum)

frame %>% 
  rbind(sum) %>% 
  datatable()
```

# 月K报告

```{r}
stock_code = "601857.SS"
stock_start = "2009-01-01"
stock_end = "2019-01-01"
list = BackTest(stock_code, stock_start, stock_end, proportion = 0.5, stop_loss = TRUE, fix_loss = 0.035, stock_interval = 'monthly')
```

Summary of Accuracy

```{r}
list$sum_accuracy
```

Forecast Plot

```{r}
list$plot
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Summary of margin

```{r}
list$p_margin
```

Data

```{r}
datatable(list$data)
```

# 周K报告

```{r}
stock_code = "601857.SS"
stock_start = "2009-01-01"
stock_end = "2019-01-01"
list = BackTest(stock_code, stock_start, stock_end, proportion = 0.5, stop_loss = TRUE, fix_loss = 0.035, stock_interval = 'weekly')
```

Summary of Accuracy

```{r}
list$sum_accuracy
```

Forecast Plot

```{r}
list$plot
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Summary of margin

```{r}
list$p_margin
```

Data

```{r}
datatable(list$data)
```

# 日K报告

```{r}
stock_code = "601857.SS"
stock_start = "2009-01-01"
stock_end = "2019-01-01"
list = BackTest(stock_code, stock_start, stock_end, proportion = 0.5, stop_loss = TRUE, fix_loss = 0.035, stock_interval = 'daily')
```

Summary of Accuracy

```{r}
list$sum_accuracy
```

Forecast Plot

```{r}
list$plot
```

Summary of margin

```{r}
datatable(list$sum_margin)
```

Summary of Stop-loss

```{r}
tryCatch(list$sum_trigger, error = "no stop_loss")
```

Summary of margin

```{r}
list$p_margin
```

Data

```{r}
datatable(list$data)
```


